### ISSUE TITLE
For help

### ISSUE THREAD

**Issue by hgbzzw** [Open-ET/openet-disalexi-beta#5]
Hi, 
I get this mistake when I run this wonderful Jupyter Notebook.
![image](https://user-images.githubusercontent.com/26102249/48859325-bfc79300-edf8-11e8-84f8-954025c5557d.png)
I change the ROI to another study area， I wanna apply this model to a new palce and test its results.
![image](https://user-images.githubusercontent.com/26102249/48859404-ebe31400-edf8-11e8-8acd-99009b04cb11.png)
![image](https://user-images.githubusercontent.com/26102249/48859439-fd2c2080-edf8-11e8-9fba-fd857d1e7a80.png)
![image](https://user-images.githubusercontent.com/26102249/48859456-0c12d300-edf9-11e8-961a-1c9ee5ed77d4.png)
I do not know why it happened? I want to know how to deal with this problem. Thanks a lot! Looking forward to your early reply!

**Comment by cgmorton** [comment]
The ALEXI data we are using only covers the the contiguous United States, so you will not be able to generate DisALEXI estimates for other areas (outside the United States).  We are definitely planning on adding support for global estimates at some point in the future, but we don't have a timeline for that work yet. 

Also, as a quick work of warning (and as the repository name indicates), this model is currently in "beta" and I would not recommend using it for any real application.

I'll make a not to add some additional text to the README making this a little more clear/obvious and probably also add an issue requesting global support.

Thanks for your interest!
